databases:
  - name: chatapps3
    databaseName: chatapps3
    user: chatapps3

services:
  - type: web
    name: chatapps3
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatapps3
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false